### PR TITLE
Upgrade spring cloud version and dependencies

### PR DESCRIPTION
**Pull request by lavcraft**

### CODE REVIEW

**Comment by aatarasoff** [comment]
Tests are failed. Need to fix it

**Comment by lavcraft** [comment]
Tests with retries is unstable. And now id dont know why :)

**Comment by aatarasoff** [comment]
@lavcraft eliminate unstable tests

And what the difference between this pull request and https://github.com/aatarasoff/spring-thrift-starter/pull/33?

**Comment by lavcraft** [comment]
Fixed :)

**Comment by lavcraft** [comment]
Fixed :)

**Pull request merged**
