### PR TITLE
Added @ThriftClientsMap for [key->ThriftClient] maps

### PR DESCRIPTION
**Pull request by jihor**
Added @ThriftClientsMap for [key->ThriftClient] maps, when callee endpoint is detemined in runtime

### CODE REVIEW

**Comment by aatarasoff** [comment]
Could you provide documentation in README.md file?

**Comment by jihor** [comment]
Provided

**Comment by aatarasoff** [comment]
Do you have twitter? Or another social account instead of github.

**Comment by jihor** [comment]
vk.com/jihor

**Comment by aatarasoff** [comment]
Ok, I will use your guthub account for mentioning you in release tweet)

**Comment by sergeevii123** [comment]
Nice job of refactoring my code in RGS and deleting me from authors, Dima

**Comment by jihor** [comment]
These changes were made on forked github code, so the headers are auto-generated. No copyright infringement intended! Feel free to change the classes' headers.

By the way, maybe we need to remove the one header contaning the RGS copyright (in the SampleMapper).

**Comment by aatarasoff** [comment]
I think it is necessary, or you need to implement your own mapper :)
Feel free to make new pull request with fix of this issue.

**Pull request merged**
