### PR TITLE
Add retry capabilities

### PR DESCRIPTION
**Pull request by jihor**
Hi!

I've added retry capabilities using `{serviceName}.maxRetries` value to retry on connection timeouts and 'no instance available' exceptions.

### CODE REVIEW

**Comment by aatarasoff** [comment]
@jihor please, fix tests

**Comment by jihor** [comment]
Hmm, strange - they passed consistently on all my machines :(
I'll look this.

**Comment by aatarasoff** [comment]
Work on my machine, yeah?)

**Comment by jihor** [comment]
It sure does :)
I'll try running a travis-ci on my fork and rewriting my tests. The existing tests are based on a counter in the callee service. If the request times out before triggering the method, it will lead to test failure. This may happen on a slow machine.

**Comment by jihor** [comment]
I've rewritten the tests to use an aspect for counting load balancer invocations.

**Pull request merged**
